# 1 EDA and Data Cleaning

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# read in data
data = pd.read_csv('../data/Crime_Data_2010_2017.csv')
data.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Weapon Description,Status Code,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location
0,1208575,03/14/2013,03/11/2013,1800,12,77th Street,1241,626,INTIMATE PARTNER - SIMPLE ASSAULT,0416 0446 1243 2000,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AO,Adult Other,626.0,NaN,NaN,NaN,6300 BRYNHURST AV,NaN,"(33.9829, -118.3338)"
1,102005556,01/25/2010,01/22/2010,2300,20,Olympic,2071,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,VAN NESS,15TH,"(34.0454, -118.3157)"
2,418,03/19/2013,03/18/2013,2030,18,Southeast,1823,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,200 E 104TH ST,NaN,"(33.942, -118.2717)"
3,101822289,11/11/2010,11/10/2010,1800,18,Southeast,1803,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,88TH,WALL,"(33.9572, -118.2717)"
4,42104479,01/11/2014,01/04/2014,2300,21,Topanga,2133,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0329,...,NaN,IC,Invest Cont,745.0,NaN,NaN,NaN,7200 CIRRUS WY,NaN,"(34.2009, -118.6369)"

In [3]:
data.columns

Index(['DR Number', 'Date Reported', 'Date Occurred', 'Time Occurred',
       'Area ID', 'Area Name', 'Reporting District', 'Crime Code',
       'Crime Code Description', 'MO Codes', 'Victim Age', 'Victim Sex',
       'Victim Descent', 'Premise Code', 'Premise Description',
       'Weapon Used Code', 'Weapon Description', 'Status Code',
       'Status Description', 'Crime Code 1', 'Crime Code 2', 'Crime Code 3',
       'Crime Code 4', 'Address', 'Cross Street', 'Location '],
      dtype='object')

In [4]:
len(data)

1584316

In [5]:
# Number of null values for each column
data.isnull().sum()

DR Number                       0
Date Reported                   0
Date Occurred                   0
Time Occurred                   0
Area ID                         0
Area Name                       0
Reporting District              0
Crime Code                      0
Crime Code Description        412
MO Codes                   171759
Victim Age                 128659
Victim Sex                 145199
Victim Descent             145232
Premise Code                   76
Premise Description          2751
Weapon Used Code          1059559
Weapon Description        1059560
Status Code                     2
Status Description              0
Crime Code 1                    7
Crime Code 2              1484319
Crime Code 3              1582133
Crime Code 4              1584247
Address                         0
Cross Street              1321583
Location                        9
dtype: int64

## 1.1 Analyze Columns and Convert them to numerical representations

In [6]:
# Prepare data by removing descriptive columns and other unimportant columns.
# Removed MO Codes because it contains a list of codes which makes it hard to analyze.
# I don't see address and cross street being particularily useful.
# Not sure what Crime Codes 1 - 4 are so we can remove them for now.
# We will use the Date Occured instead of Date reported.
data2 = data[['DR Number', 'Date Occurred', 'Time Occurred',
       'Area ID', 'Reporting District', 'Crime Code', 'Victim Age', 'Victim Sex',
       'Victim Descent', 'Premise Code',
       'Weapon Used Code', 'Status Code', 'Location ']]

### 1.1.1 Victim Sex

In [7]:
print(data2['Victim Sex'].unique())
print(data2.groupby('Victim Sex')['DR Number'].nunique())
print('Null:', data2['Victim Sex'].isnull().sum())

['F' nan 'M' 'H' 'X' '-']
Victim Sex
-         1
F    675402
H        53
M    739581
X     24080
Name: DR Number, dtype: int64
Null: 145199

In [8]:
# Turn Victim Sex into 0 for male, 1 for female, and 2 for other
data2['Victim Sex'].loc[data2['Victim Sex'] == 'M'] = 0
data2['Victim Sex'].loc[data2['Victim Sex'] == 'F'] = 1
data2['Victim Sex'].loc[data2['Victim Sex'].isna()] = 2
data2['Victim Sex'].loc[data2['Victim Sex'] == '-'] = 2
data2['Victim Sex'].loc[data2['Victim Sex'] == 'H'] = 2
data2['Victim Sex'].loc[data2['Victim Sex'] == 'X'] = 2

/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [9]:
data2.head()

,DR Number,Date Occurred,Time Occurred,Area ID,Reporting District,Crime Code,Victim Age,Victim Sex,Victim Descent,Premise Code,Weapon Used Code,Status Code,Location
0,1208575,03/11/2013,1800,12,1241,626,30.0,1,W,502.0,400.0,AO,"(33.9829, -118.3338)"
1,102005556,01/22/2010,2300,20,2071,510,NaN,2,NaN,101.0,NaN,IC,"(34.0454, -118.3157)"
2,418,03/18/2013,2030,18,1823,510,12.0,2,NaN,101.0,NaN,IC,"(33.942, -118.2717)"
3,101822289,11/10/2010,1800,18,1803,510,NaN,2,NaN,101.0,NaN,IC,"(33.9572, -118.2717)"
4,42104479,01/04/2014,2300,21,2133,745,84.0,0,W,501.0,NaN,IC,"(34.2009, -118.6369)"

In [10]:
# check that it worked
print(data2['Victim Sex'].unique())

[1 2 0]

### 1.1.2 Victim Descent

In [11]:
# Pulled from: https://ambarishg.github.io/books/LittleBookDataViz/victim-descent.html
VictimDescentAbbr = ("A","B","C","D","F","G","H","I","J","K","L","O","P","S","U","V","W","X","Z")
VictimDescentDescription = ("Other Asian","Black",
                             "Chinese","Cambodian","Filipino",
                             "Guamanian","Hispanic/Latin/Mexican",
                             "American Indian/Alaskan Native",
                             "Japanese","Korean","Laotian ",
                             "Other","Pacific Islander",
                             "Samoan","Hawaiian","Vietnamese",
                             "White","Unknown","AsianIndian")

In [12]:
print(data2['Victim Descent'].unique())
print(data2.groupby('Victim Descent')['DR Number'].nunique())
print('Null:', data2['Victim Descent'].isnull().sum())

['W' nan 'O' 'H' 'B' 'A' 'X' 'F' 'I' 'K' 'G' 'C' 'J' 'Z' 'P' 'V' 'U' 'L'
 'S' 'D' '-']
Victim Descent
-         1
A     37143
B    255056
C       618
D        15
F      1885
G        61
H    549515
I       663
J       237
K      7136
L        10
O    152776
P       276
S        24
U       137
V        86
W    391855
X     41535
Z        55
Name: DR Number, dtype: int64
Null: 145232

In [13]:
# The dictionary for the descent codes
descent_dict = [[0, None, None]]
for i in range(len(VictimDescentAbbr)):
    descent_dict.append([i+1, VictimDescentAbbr[i], VictimDescentDescription[i]])
descent_dict

[[0, None, None],
 [1, 'A', 'Other Asian'],
 [2, 'B', 'Black'],
 [3, 'C', 'Chinese'],
 [4, 'D', 'Cambodian'],
 [5, 'F', 'Filipino'],
 [6, 'G', 'Guamanian'],
 [7, 'H', 'Hispanic/Latin/Mexican'],
 [8, 'I', 'American Indian/Alaskan Native'],
 [9, 'J', 'Japanese'],
 [10, 'K', 'Korean'],
 [11, 'L', 'Laotian '],
 [12, 'O', 'Other'],
 [13, 'P', 'Pacific Islander'],
 [14, 'S', 'Samoan'],
 [15, 'U', 'Hawaiian'],
 [16, 'V', 'Vietnamese'],
 [17, 'W', 'White'],
 [18, 'X', 'Unknown'],
 [19, 'Z', 'AsianIndian']]

In [14]:
# Assign each letter a number, 'nan' and '-' should get 0

data2['Victim Descent'].loc[data2['Victim Descent'] == '-'] = 0
data2['Victim Descent'].loc[data2['Victim Descent'].isna()] = 0

for i in range(len(VictimDescentAbbr)):
    data2['Victim Descent'].loc[data2['Victim Descent'] == VictimDescentAbbr[i]] = i + 1

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [15]:
# Check to see that it worked
print(data2['Victim Descent'].unique())

[17  0 12  7  2  1 18  5  8 10  6  3  9 19 13 16 15 11 14  4]

### 1.1.3 Victim Age

In [16]:
print(data2['Victim Age'].unique())
#print(data2.groupby('Victim Age')['DR Number'].nunique())
#print('Null:', data2['Victim Age'].isnull().sum())

[30. nan 12. 84. 49. 27. 42. 29. 19. 23. 39. 18. 25. 34. 37. 50. 20. 32.
 24. 48. 45. 60. 40. 46. 22. 53. 36. 57. 56. 26. 52. 33. 21. 59. 28. 35.
 51. 41. 11. 10. 31. 43. 38. 73. 58. 70. 62. 55. 13. 66. 15. 68. 61. 63.
 54. 69. 44. 47. 14. 64. 93. 72. 65. 92. 75. 88. 97. 82. 17. 16. 81. 74.
 67. 71. 83. 77. 78. 80. 76. 99. 89. 79. 86. 94. 90. 85. 95. 91. 87. 96.
 98.]

### 1.1.4 Location

In [17]:
data2['Location '].head()

0    (33.9829, -118.3338)
1    (34.0454, -118.3157)
2     (33.942, -118.2717)
3    (33.9572, -118.2717)
4    (34.2009, -118.6369)
Name: Location , dtype: object

In [74]:
# Very slow computation
# Split the location into two seperate columns, longitude and latitude
templist = []
for i in range(len(data2['Location '])):
    try:
        temp = data2['Location '][i].split(',')
        templist.append([float(temp[0][1:]), float(temp[1][:-1])])
    except AttributeError:
        templist.append([np.nan, np.nan])
        print('AttributeError on value:', data2['Location '][i])

templist

AttributeError on value: nan
AttributeError on value: nan
AttributeError on value: nan
AttributeError on value: nan
AttributeError on value: nan
AttributeError on value: nan
AttributeError on value: nan
AttributeError on value: nan
AttributeError on value: nan

[[33.9829, -118.3338],
 [34.0454, -118.3157],
 [33.942, -118.2717],
 [33.9572, -118.2717],
 [34.2009, -118.6369],
 [34.0591, -118.2412],
 [34.1211, -118.2048],
 [34.241, -118.3987],
 [34.3147, -118.4589],
 [34.2012, -118.4662],
 [34.2354, -118.4517],
 [34.0294, -118.2671],
 [33.9651, -118.2783],
 [33.9651, -118.2754],
 [34.2012, -118.416],
 [33.9456, -118.2652],
 [34.0431, -118.2536],
 [34.0503, -118.2504],
 [34.0352, -118.2583],
 [34.048, -118.2577],
 [34.045, -118.264],
 [34.0407, -118.268],
 [34.0423, -118.2452],
 [34.0517, -118.2456],
 [34.0435, -118.2471],
 [34.0395, -118.2656],
 [34.2139, -118.4793],
 [34.0581, -118.2371],
 [34.0688, -118.2333],
 [34.0482, -118.2472],
 [34.0423, -118.2452],
 [34.045, -118.264],
 [34.045, -118.264],
 [34.051, -118.248],
 [34.0632, -118.2408],
 [34.0467, -118.2427],
 [34.043, -118.2341],
 [34.0423, -118.2452],
 [34.0451, -118.2604],
 [34.0503, -118.2433],
 [34.255, -118.4103],
 [34.043, -118.2606],
 [34.1351, -118.2153],
 [34.064, -118.2375],
 [34.0458, -118.243],
 [34.0627, -118.2463],
 [34.0412, -118.2474],
 [34.0552, -118.2322],
 [34.0476, -118.2477],
 [34.0405, -118.2567],
 [34.0383, -118.254],
 [34.0481, -118.2542],
 [34.0688, -118.2394],
 [34.0388, -118.2676],
 [34.0415, -118.2654],
 [34.048, -118.2577],
 [34.0363, -118.2573],
 [34.0482, -118.2472],
 [34.0442, -118.2439],
 [34.0619, -118.2369],
 [34.0401, -118.2533],
 [34.0402, -118.2598],
 [34.045, -118.264],
 [34.0479, -118.2612],
 [34.0482, -118.2472],
 [34.0619, -118.2369],
 [34.065, -118.2418],
 [34.0381, -118.2629],
 [34.0433, -118.2504],
 [34.0437, -118.2617],
 [34.0381, -118.2629],
 [34.0381, -118.2327],
 [34.0449, -118.2458],
 [34.0401, -118.2668],
 [34.0467, -118.247],
 [34.0494, -118.2581],
 [34.0446, -118.249],
 [34.0408, -118.2428],
 [34.0446, -118.249],
 [34.0452, -118.2534],
 [34.0481, -118.2507],
 [34.0481, -118.2507],
 [34.0419, -118.2485],
 [34.0482, -118.2472],
 [34.045, -118.264],
 [34.0423, -118.2452],
 [34.0423, -118.2452],
 [34.0449, -118.2528],
 [34.0402, -118.2329],
 [34.0433, -118.2504],
 [34.0407, -118.2541],
 [34.0627, -118.2463],
 [33.9651, -118.2783],
 [34.0896, -118.2105],
 [34.048, -118.2577],
 [34.0825, -118.25],
 [34.1059, -118.1958],
 [33.9738, -118.2739],
 [33.9824, -118.2827],
 [33.9872, -118.3399],
 [33.9722, -118.2695],
 [33.9869, -118.2739],
 [34.0294, -118.2671],
 [34.0372, -118.2654],
 [33.9834, -118.2718],
 [33.9971, -118.2449],
 [34.0633, -118.229],
 [34.045, -118.264],
 [33.9844, -118.2652],
 [33.9851, -118.2783],
 [34.0039, -118.2392],
 [34.0073, -118.2784],
 [34.0057, -118.2497],
 [34.0633, -118.229],
 [34.0294, -118.2671],
 [34.0472, -118.2371],
 [34.0361, -118.2634],
 [34.0285, -118.2691],
 [33.9834, -118.2695],
 [34.0283, -118.2711],
 [34.0225, -118.2633],
 [34.0259, -118.2535],
 [33.9489, -118.3939],
 [33.9759, -118.4156],
 [33.967, -118.396],
 [33.9886, -118.473],
 [34.001, -118.4129],
 [34.2048, -118.3649],
 [34.1649, -118.3774],
 [34.0631, -118.2337],
 [34.2012, -118.4247],
 [34.2754, -118.4181],
 [34.2661, -118.4221],
 [34.2531, -118.429],
 [34.2409, -118.4132],
 [34.0565, -118.2411],
 [34.0451, -118.2604],
 [33.9757, -118.3338],
 [34.1146, -118.2408],
 [34.0452, -118.2534],
 [34.0285, -118.2391],
 [34.0445, -118.2523],
 [34.0423, -118.2595],
 [34.0494, -118.2599],
 [34.0446, -118.249],
 [34.0581, -118.2371],
 [34.1865, -118.6277],
 [34.2746, -118.5586],
 [34.2214, -118.4756],
 [34.25, -118.5273],
 [33.9378, -118.2542],
 [34.2902, -118.4508],
 [34.2309, -118.4644],
 [34.0446, -118.245],
 [33.9591, -118.2717],
 [33.9271, -118.276],
 [34.0449, -118.2458],
 [34.0446, -118.245],
 [33.9443, -118.2462],
 [33.9374, -118.2695],
 [34.0583, -118.2378],
 [34.0494, -118.2599],
 [34.245, -118.4502],
 [34.2145, -118.4309],
 [34.2416, -118.4371],
 [34.2355, -118.4589],
 [34.0545, -118.2999],
 [34.0691, -118.2917],
 [34.0637, -118.287],
 [34.0672, -118.3128],
 [34.0426, -118.2412],
 [34.0544, -118.2378],
 [34.0615, -118.2412],
 [34.0393, -118.2729],
 [34.0312, -118.2615],
 [34.0371, -118.2551],
 [34.0535, -118.256],
 [34.0481, -118.2507],
 [34.0449, -118.2458],
 [34.0419, -118.2523],
 [34.0487, -118.2571],
 [34.0499, -118.2614],
 [34.2047, -118.6158],
 [34.0617, -118.2469],
 [34.0446, -118.249],
 [34.0454, -118.2422],
 [34.0453, -118.2499],
 [34.0628, -118.242],
 [34.0442, -118.2439],
 [34.0535, -118.256],
 [34.0522, -118.2434],
 [34.048, -118.2577],
 [34.3797, -118.5286],
 [34.0363, -118.2733],
 [34.0481, -118.2507],
 [34.0459, -118.2545],
 [33.9685, -118.2564],
 [34.0446, -118.245],
 [34.0428, -118.2461],
 [34.0402, -118.2633],
 [34.0371, -118.2551],
 [34.0405, -118.2604],
 [34.0423, -118.2452],
 [34.0423, -118.2666],
 [34.0277, -118.2574],
 [34.0481, -118.2542],
 [34.0446, -118.245],
 [34.0378, -118.2561],
 [34.0407, -118.2468],
 [34.0391, -118.2617],
 [34.045, -118.264],
 [34.0433, -118.2504],
 [34.048, -118.2577],
 [34.0516, -118.2561],
 [34.0419, -118.2485],
 [34.0453, -118.2499],
 [34.0445, -118.2523],
 [34.0461, -118.2476],
 [34.0419, -118.2485],
 [34.0591, -118.2412],
 [34.0423, -118.2595],
 [34.0423, -118.2666],
 [34.0375, -118.2423],
 [34.0446, -118.249],
 [34.0403, -118.2421],
 [34.0423, -118.2452],
 [34.0446, -118.245],
 [34.0461, -118.2476],
 [34.0258, -118.2708],
 [34.0516, -118.2561],
 [34.0424, -118.2493],
 [34.0389, -118.2643],
 [34.0437, -118.2652],
 [34.0473, -118.2566],
 [34.0324, -118.2675],
 [34.0407, -118.2468],
 [34.0446, -118.245],
 [34.048, -118.2577],
 [34.0635, -118.2313],
 [34.0635, -118.2313],
 [34.048, -118.2577],
 [34.045, -118.264],
 [34.0407, -118.2468],
 [34.0256, -118.2349],
 [34.0578, -118.2371],
 [34.0467, -118.2485],
 [34.0442, -118.268],
 [34.0565, -118.2411],
 [34.0981, -118.2054],
 [34.0317, -118.2626],
 [33.9873, -118.4706],
 [34.0631, -118.2337],
 [34.0439, -118.2514],
 [34.0439, -118.2514],
 [34.046, -118.2509],
 [34.0494, -118.2599],
 [34.0446, -118.245],
 [34.0494, -118.2599],
 [34.0454, -118.2422],
 [34.0466, -118.2427],
 [34.0473, -118.2425],
 [34.0459, -118.2351],
 [34.0504, -118.2409],
 [34.1903, -118.5262],
 [34.0891, -118.2662],
 [34.1107, -118.2027],
 [34.1118, -118.2918],
 [33.9688, -118.2695],
 [34.0571, -118.2509],
 [33.9747, -118.2783],
 [33.9892, -118.2915],
 [33.982, -118.2652],
 [34.0296, -118.2299],
 [34.2536, -118.4266],
 [34.0437, -118.2652],
 [34.0364, -118.2603],
 [34.1785, -118.4137],
 [34.1577, -118.3637],
 [34.1811, -118.3615],
 [34.2103, -118.3954],
 [34.1448, -118.3926],
 [34.043, -118.242],
 [34.2428, -118.5361],
 [34.0423, -118.2452],
 [34.1831, -118.3833],
 [34.2738, -118.4847],
 [34.1613, -118.3615],
 [34.2012, -118.3834],
 [33.9529, -118.2651],
 [34.2639, -118.3383],
 [34.2679, -118.3008],
 [34.2625, -118.4361],
 [34.2175, -118.3618],
 [34.2244, -118.384],
 [34.2543, -118.3105],
 [34.2439, -118.4164],
 [34.2535, -118.4032],
 [34.2345, -118.3713],
 [34.2445, -118.4155],
 [34.0435, -118.2427],
 [34.2246, -118.5885],
 [34.2868, -118.4117],
 [34.2782, -118.4225],
 [34.2679, -118.3008],
 [34.2103, -118.3725],
 [34.2321, -118.3964],
 [34.0532, -118.2425],
 [34.0582, -118.2387],
 [34.2267, -118.5026],
 [34.0407, -118.2468],
 [34.2517, -118.6039],
 [34.2518, -118.6061],
 [33.931, -118.2522],
 [34.0495, -118.2494],
 [34.2575, -118.498],
 [33.931, -118.287],
 [34.2284, -118.4851],
 [33.9483, -118.2329],
 [34.23, -118.5667],
 [34.0446, -118.245],
 [34.25, -118.5973],
 [34.2246, -118.5383],
 [34.272, -118.4978],
 [34.2564, -118.5536],
 [34.2213, -118.4896],
 [34.2273, -118.5536],
 [34.0578, -118.252],
 [34.2627, -118.5274],
 [34.2564, -118.5536],
 [34.2445, -118.6148],
 [34.2264, -118.5667],
 [33.9351, -118.2542],
 [34.0488, -118.2518],
 [34.0488, -118.2518],
 [33.9432, -118.2462],
 [34.2283, -118.4655],
 [34.051, -118.248],
 [34.0534, -118.2409],
 [34.0412, -118.2436],
 [34.0419, -118.2485],
 [34.0459, -118.2579],
 [34.045, -118.2435],
 [34.0423, -118.2452],
 [34.051, -118.2445],
 [33.9698, -118.2827],
 [34.04, -118.2876],
 [34.0442, -118.2439],
 [34.0494, -118.2599],
 [34.0515, -118.2424],
 [34.0417, -118.2443],
 [34.0544, -118.2535],
 [34.0433, -118.2504],
 [34.0415, -118.2654],
 [34.0472, -118.2442],
 [34.0566, -118.2319],
 [34.0518, -118.2842],
 [34.2353, -118.4404],
 [34.267, -118.4525],
 [34.0799, -118.3069],
 [34.0496, -118.2458],
 [34.0383, -118.254],
 [34.0467, -118.252],
 [34.0481, -118.2542],
 [34.0377, -118.2621],
 [34.0423, -118.2452],
 [34.0407, -118.2468],
 [34.0455, -118.2381],
 [34.0405, -118.2567],
 [34.0442, -118.2439],
 [34.046, -118.2509],
 [34.0327, -118.2683],
 [34.0459, -118.2545],
 [34.0407, -118.2468],
 [34.0375, -118.2423],
 [34.0595, -118.2368],
 [34.0595, -118.2368],
 [34.0578, -118.252],
 [34.0446, -118.249],
 [34.0383, -118.2633],
 [34.2212, -118.5027],
 [34.032, -118.2667],
 [34.0407, -118.2541],
 [34.0623, -118.2383],
 [34.0396, -118.2558],
 [34.0382, -118.2384],
 [34.0494, -118.2599],
 [34.0474, -118.2496],
 [34.2085, -118.4837],
 [34.2336, -118.5976],
 [34.1866, -118.5011],
 [34.1227, -118.1988],
 [34.106, -118.1948],
 [34.1273, -118.2011],
 [34.1251, -118.2024],
 [34.1391, -118.2141],
 [34.1054, -118.1923],
 [33.9708, -118.2803],
 [33.9646, -118.3046],
 [33.9583, -118.3003],
 [34.0423, -118.2452],
 [33.9455, -118.2869],
 [33.9538, -118.2782],
 [33.9419, -118.2805],
 [34.2124, -118.44],
 [34.0363, -118.2619],
 [34.192, -118.5762],
 [34.0416, -118.2584],
 [34.0481, -118.2507],
 [34.0606, -118.2439],
 [34.0446, -118.245],
 [34.0403, -118.2421],
 [34.0423, -118.2678],
 [34.0011, -118.242],
 [34.189, -118.5492],
 [34.0423, -118.2666],
 [34.0982, -118.2863],
 [34.0424, -118.2493],
 [34.0643, -118.2299],
 [34.0333, -118.262],
 [33.9638, -118.2564],
 [33.9931, -118.3308],
 [33.9746, -118.2944],
 [34.1713, -118.5098],
 [34.0717, -118.2493],
 [33.96, -118.2917],
 [33.9984, -118.2499],
 [33.9932, -118.3258],
 [33.9713, -118.2695],
 [33.9874, -118.2827],
 [33.9601, -118.2827],
 [34.0423, -118.2452],
 [34.0001, -118.3149],
 [34.0489, -118.2453],
 [34.0218, -118.2665],
 [34.0293, -118.241],
 [34.0473, -118.2601],
 [34.0056, -118.274],
 [34.0242, -118.2472],
 [34.0454, -118.2466],
 [34.0326, -118.23],
 [33.9916, -118.2564],
 [34.0154, -118.2678],
 [33.9984, -118.2521],
 [33.9994, -118.2388],
 [34.0025, -118.2652],
 [34.0211, -118.2302],
 [34.0401, -118.2668],
 [34.0039, -118.2565],
 [34.0306, -118.23],
 [33.9933, -118.2783],
 [34.0011, -118.242],
 [33.9935, -118.2579],
 [34.0296, -118.2614],
 [34.0337, -118.2533],
 [33.9943, -118.2739],
 [33.9869, -118.2783],
 [34.0502, -118.254],
 [33.9309, -118.3875],
 [34.0037, -118.4335],
 [33.9881, -118.4708],
 [33.9898, -118.4491],
 [33.9964, -118.4575],
 [33.9669, -118.4566],
 [34.0242, -118.4183],
 [34.046, -118.2509],
 [33.9895, -118.4524],
 [34.0272, -118.3977],
 [34.0243, -118.4084],
 [33.9698, -118.2827],
 [33.9985, -118.462],
 [33.9926, -118.4744],
 [34.0248, -118.4021],
 [33.9633, -118.4197],
 [34.0435, -118.2471],
 [34.2085, -118.3856],
 [34.1576, -118.3965],
 [34.0439, -118.2399],
 [34.2832, -118.4102],
 [34.2287, -118.3663],
 [34.0346, -118.2323],
 [34.2289, -118.5361],
 [34.2391, -118.5338],
 [34.2572, -118.5973],
 [34.272, -118.5022],
 [33.9572, -118.2739],
 [33.9501, -118.2827],
 [34.2717, -118.4459],
 [34.2232, -118.4488],
 [34.2482, -118.4489],
 [34.2428, -118.4675],
 [34.2282, -118.4553],
 [34.2683, -118.4714],
 [34.3043, -118.4726],
 [34.3009, -118.441],
 [34.2427, -118.4502],
 [34.3009, -118.4442],
 [34.321, -118.4478],
 [34.309, -118.4515],
 [34.2283, -118.4611],
 [34.2538, -118.4538],
 [34.2388, -118.418],
 [34.2393, -118.4462],
 [34.2301, -118.4698],
 [34.2216, -118.4488],
 [34.0319, -118.2594],
 [34.0384, -118.2646],
 [34.2215, -118.46],
 [34.2301, -118.4698],
 [34.2803, -118.4589],
 [34.3021, -118.4467],
 [34.2269, -118.4394],
 [34.25, -118.4587],
 [34.0405, -118.2567],
 [34.3076, -118.4562],
 [34.0934, -118.295],
 [34.2215, -118.4553],
 [34.2396, -118.4337],
 [34.2279, -118.4516],
 [34.0405, -118.2567],
 [34.043, -118.2606],
 [34.0738, -118.3004],
 [34.0753, -118.2994],
 [34.056, -118.2941],
 [34.04, -118.2883],
 [34.0777, -118.3045],
 [34.0559, -118.302],
 [34.0597, -118.3042],
 [34.04, -118.2877],
 [34.0509, -118.3041],
 [34.0777, -118.3023],
 [34.0472, -118.301],
 [34.0382, -118.2889],
 [34.0487, -118.2588],
 [34.0617, -118.3048],
 [34.0545, -118.2976],
 [34.0446, -118.245],
 [34.0575, -118.2516],
 [34.0577, -118.2976],
 [34.1489, -118.621],
 [34.1939, -118.4836],
 [34.0416, -118.255],
 [34.0526, -118.2989],
 [34.0578, -118.2371],
 [34.0401, -118.2533],
 [34.207, -118.644],
 [34.1865, -118.6256],
 [34.2196, -118.6292],
 [34.1618, -118.6302],
 [34.1792, -118.6059],
 [34.1744, -118.6016],
 [34.0423, -118.2561],
 [34.198, -118.6246],
 [34.1905, -118.6059],
 [34.2194, -118.6235],
 [34.2106, -118.5896],
 [34.1872, -118.571],
 [34.1875, -118.603],
 [34.0423, -118.2561],
 [34.0423, -118.2452],
 [34.0621, -118.2376],
 [34.0481, -118.2542],
 [34.0495, -118.2494],
 [34.1173, -118.2371],
 [34.0897, -118.2561],
 [34.0391, -118.2581],
 [34.2992, -118.4191],
 [34.0763, -118.2966],
 [34.0419, -118.2485],
 [34.0673, -118.2354],
 [34.045, -118.2435],
 [34.0423, -118.2595],
 [34.0674, -118.2468],
 [33.9933, -118.2842],
 [33.9779, -118.2652],
 [34.0674, -118.2954],
 [33.997, -118.4761],
 [34.0649, -118.2289],
 [34.212, -118.5754],
 [34.1773, -118.5988],
 [34.212, -118.5754],
 [34.0395, -118.2656],
 [34.0395, -118.2656],
 [34.0111, -118.4293],
 [34.0449, -118.2458],
 [34.0344, -118.23],
 [33.9627, -118.4217],
 [34.0474, -118.2496],
 [34.0613, -118.2352],
 [34.0606, -118.2439],
 [34.0423, -118.2452],
 [34.0538, -118.2488],
 [34.0446, -118.245],
 [34.0398, -118.2413],
 [34.0449, -118.2415],
 [34.0416, -118.2584],
 [34.0446, -118.249],
 [34.0912, -118.2111],
 [34.0627, -118.2463],
 [34.0435, -118.2427],
 [34.1734, -118.536],
 [33.977, -118.2739],
 [34.0599, -118.2655],
 [34.0452, -118.2534],
 [34.0438, -118.2397],
 [34.0449, -118.2458],
 [34.0606, -118.2439],
 [34.0661, -118.2476],
 [34.0442, -118.2439],
 [34.0435, -118.2427],
 [34.0451, -118.2604],
 [34.043, -118.2571],
 [34.035, -118.2607],
 [34.0499, -118.2614],
 [34.1174, -118.1972],
 [34.0371, -118.2551],
 [34.0452, -118.2569],
 [34.0317, -118.2641],
 [34.0408, -118.2428],
 [34.0398, -118.2413],
 [34.0405, -118.2604],
 [34.0459, -118.2657],
 [34.1107, -118.2027],
 [34.0381, -118.2511],
 [34.0494, -118.2599],
 [34.0436, -118.2354],
 [34.0407, -118.2468],
 [33.9983, -118.3089],
 [34.0474, -118.2496],
 [33.9892, -118.2915],
 [34.1232, -118.2064],
 [34.1007, -118.2602],
 [34.113, -118.1825],
 [34.0359, -118.2344],
 [33.9932, -118.3177],
 [34.0473, -118.2601],
 [33.9746, -118.2918],
 [33.9965, -118.4805],
 [34.11, -118.192],
 [33.9824, -118.2739],
 [34.0199, -118.2601],
 [33.9985, -118.2696],
 [34.0029, -118.274],
 [34.0011, -118.274],
 [34.0141, -118.277],
 [34.0935, -118.2866],
 [33.9934, -118.2739],
 [34.0474, -118.2496],
 [34.0011, -118.274],
 [34.0128, -118.2541],
 [34.0082, -118.2728],
 [34.0627, -118.2463],
 [34.0184, -118.2633],
 [34.0281, -118.268],
 [34.0039, -118.2521],
 [33.9958, -118.2617],
 [34.0288, -118.3996],
 [34.0082, -118.4305],
 [34.0668, -118.2359],
 [33.9728, -118.2783],
 [34.0016, -118.2389],
 [33.9708, -118.2783],
 [34.0452, -118.2569],
 [34.2935, -118.4598],
 [34.001, -118.2783],
 [34.0149, -118.2689],
 [33.9843, -118.2695],
 [33.993, -118.2411],
 [34.012, -118.4284],
 [34.0164, -118.2699],
 [34.0243, -118.4028],
 [33.994, -118.4074],
 [33.9569, -118.3847],
 [34.145, -118.3822],
 [34.1558, -118.3943],
 [34.2103, -118.3681],
 [34.2588, -118.5951],
 [34.053, -118.2548],
 [34.2748, -118.5621],
 [34.2391, -118.5361],
 [33.9383, -118.2781],
 [33.9587, -118.2869],
 [33.9123, -118.2827],
 [34.048, -118.2577],
 [33.9433, -118.2541],
 [33.9438, -118.2652],
 [33.9581, -118.2651],
 [34.2152, -118.4488],
 [33.9824, -118.4679],
 [34.0649, -118.2289],
 [34.0008, -118.2565],
 [33.9797, -118.2652],
 [34.0419, -118.2485],
 [34.045, -118.264],
 [34.0763, -118.2975],
 [34.0453, -118.2499],
 [34.0617, -118.3091],
 [34.1732, -118.6152],
 [34.0545, -118.2499],
 [34.0086, -118.4246],
 [34.0052, -118.4478],
 [34.2868, -118.4081],
 [34.1849, -118.3878],
 [34.1831, -118.4073],
 [34.0473, -118.2566],
 [34.0423, -118.2666],
 [34.2156, -118.6003],
 [34.0617, -118.2469],
 [34.2624, -118.4272],
 [34.2522, -118.5234],
 [34.2264, -118.5466],
 [34.2282, -118.4575],
 [33.9433, -118.2462],
 [34.3043, -118.4726],
 [34.0686, -118.2266],
 [34.0654, -118.2929],
 [34.0491, -118.3031],
 [34.2083, -118.6234],
 [34.166, -118.6233],
 [34.1829, -118.6059],
 [34.1974, -118.6044],
 [34.0467, -118.2485],
 [34.1938, -118.599],
 [34.0488, -118.2518],
 [34.0395, -118.2656],
 [34.0371, -118.2551],
 [34.032, -118.2657],
 [34.0705, -118.2857],
 [34.0435, -118.2427],
 [34.0481, -118.2542],
 [34.0417, -118.2443],
 [34.0453, -118.2499],
 [34.0494, -118.2599],
 [34.1811, -118.6059],
 [34.2176, -118.606],
 [34.048, -118.2577],
 [34.0442, -118.2439],
 [34.048, -118.2577],
 [33.9516, -118.3754],
 [33.9424, -118.2869],
 [33.9237, -118.2543],
 [34.0444, -118.2628],
 [34.0391, -118.2659],
 [34.0502, -118.2574],
 [34.0494, -118.2599],
 [34.0336, -118.23],
 [33.9993, -118.2608],
 [34.0306, -118.2635],
 [34.0473, -118.2566],
 [34.0437, -118.2617],
 [33.9974, -118.2813],
 [34.0433, -118.2504],
 [34.048, -118.2577],
 [34.0435, -118.2427],
 [34.0428, -118.2461],
 [34.0488, -118.2483],
 [34.0504, -118.2409],
 [34.0446, -118.245],
 [34.0395, -118.2656],
 [34.064, -118.2375],
 [34.0357, -118.2593],
 [34.0395, -118.2527],
 [34.0454, -118.2657],
 [34.0503, -118.2433],
 [34.045, -118.264],
 [34.045, -118.264],
 [34.045, -118.264],
 [34.0489, -118.2519],
 [34.0515, -118.2424],
 [34.0449, -118.2458],
 [34.0492, -118.2488],
 [34.0346, -118.2572],
 [34.0419, -118.2485],
 [34.0494, -118.2599],
 [34.0481, -118.2507],
 [34.0433, -118.2504],
 [34.0635, -118.228],
 [33.9878, -118.4215],
 [34.2048, -118.5339],
 [34.0405, -118.2567],
 [34.0736, -118.2312],
 [34.0658, -118.2365],
 [34.0363, -118.2573],
 [34.0509, -118.2585],
 [34.0509, -118.2585],
 [34.0473, -118.2566],
 [34.0464, -118.2447],
 [34.0435, -118.2471],
 [34.0449, -118.2528],
 [34.053, -118.2513],
 [34.0449, -118.2458],
 [34.0316, -118.2657],
 [34.0431, -118.2536],
 [34.0504, -118.2409],
 [34.0409, -118.2609],
 [34.048, -118.2577],
 [34.0473, -118.2566],
 [34.0464, -118.248],
 [34.0538, -118.2488],
 [34.0516, -118.2561],
 [34.0426, -118.2412],
 [34.0446, -118.245],
 [34.0481, -118.2507],
 [34.0442, -118.2439],
 [34.0464, -118.2447],
 [34.0537, -118.2455],
 [34.0453, -118.2499],
 [34.0445, -118.2523],
 [33.9907, -118.2422],
 [34.0633, -118.229],
 [34.0446, -118.249],
 [34.0412, -118.2436],
 [34.0474, -118.2496],
 [33.9564, -118.1586],
 [34.0481, -118.2542],
 [34.051, -118.248],
 [34.1557, -118.4697],
 [34.1903, -118.5317],
 [34.2084, -118.5174],
 [34.2084, -118.5557],
 [34.2158, -118.3965],
 [34.051, -118.248],
 [34.1364, -118.1903],
 [34.1335, -118.2158],
 [34.0669, -118.2275],
 [34.1154, -118.1809],
 [34.1098, -118.1984],
 [34.1199, -118.2431],
 [34.0839, -118.2224],
 [33.9719, -118.3228],
 [33.9633, -118.2783],
 [33.9708, -118.2783],
 [34.0409, -118.2609],
 [33.9892, -118.3089],
 [33.9735, -118.3014],
 [33.9891, -118.327],
 [33.9665, -118.2929],
 [33.9747, -118.2695],
 [33.9602, -118.2651],
 [34.0372, -118.2654],
 [33.999, -118.3113],
 [34.0326, -118.23],
 [33.9878, -118.2675],
 [34.0011, -118.2565],
 [34.0533, -118.2379],
 [34.0467, -118.2485],
 [34.0454, -118.2466],
 [33.9976, -118.2608],
 [33.9907, -118.2739],
 [34.0442, -118.2439],
 [34.0423, -118.2452],
 [33.9916, -118.2739],
 [34.0439, -118.2479],
 [33.9969, -118.4598],
 [34.0187, -118.4069],
 [34.0549, -118.2426],
 [33.9759, -118.4156],
 [33.9757, -118.462],
 [33.9985, -118.4038],
 [34.046, -118.2509],
 [34.0516, -118.2561],
 [34.0317, -118.2641],
 [34.2048, -118.3627],
 [34.1758, -118.3855],
 [33.9872, -118.2652],
 [34.2399, -118.3678],
 [34.2621, -118.4385],
 [34.0518, -118.2493],
 [34.2217, -118.4053],
 [34.0674, -118.2941],
 [34.2817, -118.4006],
 [34.2374, -118.3964],
 [34.2808, -118.5542],
 [34.2519, -118.561],
 [34.0502, -118.254],
 [34.2748, -118.5621],
 [34.2573, -118.5985],
 [34.2564, -118.5536],
 [34.0423, -118.2452],

In [75]:
data2['Longitude'] = [item[0] for item in templist]
data2['Latitude'] = [item[1] for item in templist]

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [76]:
data2.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Reporting District,Crime Code,Victim Age,Victim Sex,Victim Descent,Premise Code,Weapon Used Code,Status Code,Location,Longitude,Latitude
0,1208575,2013-03-14,2013-03-11,1800,12,1241,626,30.0,1,17,502.0,400.0,AO,"(33.9829, -118.3338)",33.9829,-118.3338
1,102005556,2010-01-25,2010-01-22,2300,20,2071,510,NaN,2,0,101.0,NaN,IC,"(34.0454, -118.3157)",34.0454,-118.3157
2,418,2013-03-19,2013-03-18,2030,18,1823,510,12.0,2,0,101.0,NaN,IC,"(33.942, -118.2717)",33.9420,-118.2717
3,101822289,2010-11-11,2010-11-10,1800,18,1803,510,NaN,2,0,101.0,NaN,IC,"(33.9572, -118.2717)",33.9572,-118.2717
4,42104479,2014-01-11,2014-01-04,2300,21,2133,745,84.0,0,17,501.0,NaN,IC,"(34.2009, -118.6369)",34.2009,-118.6369

### 1.1.5 Status Code (removed from final dataset)

In [18]:
print(data2['Status Code'].unique())
print(data2.groupby('Status Code')['DR Number'].nunique())
print('Null:', data2['Status Code'].isnull().sum())

['AO' 'IC' 'AA' 'JA' 'JO' nan 'CC' 'TH' '13' '19']
Status Code
13          1
19          1
AA     162424
AO     178175
CC         24
IC    1227180
JA      12619
JO       3889
TH          1
Name: DR Number, dtype: int64
Null: 2

In [19]:
print(data['Status Description'].unique())
print(data.groupby('Status Description')['DR Number'].nunique())
print('Null:', data['Status Description'].isnull().sum())

['Adult Other' 'Invest Cont' 'Adult Arrest' 'Juv Arrest' 'Juv Other' 'UNK']
Status Description
Adult Arrest     162424
Adult Other      178175
Invest Cont     1227180
Juv Arrest        12619
Juv Other          3889
UNK                  29
Name: DR Number, dtype: int64
Null: 0

### 1.1.6 Date Occurred

In [20]:
# Print number of nulls
print('Null:', data2['Date Occurred'].isnull().sum())

Null: 0

In [25]:
# convert to datetime
data2['Date Occurred'] = pd.to_datetime(data2['Date Occurred'], format='%m/%d/%Y')

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [26]:
# Seperate the date column into month, day, year
data2['Month'] = data2['Date Occurred'].dt.month
data2['Day'] = data2['Date Occurred'].dt.day
data2['Year'] = data2['Date Occurred'].dt.year

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

### 1.1.7 Weapon Used Code

In [57]:
weap_dict = make_dict(data, 'Weapon Used Code', 'Weapon Description')

In [58]:
weap_dict

[[],
 [400.0, 'STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)'],
 [500.0, 'UNKNOWN WEAPON/OTHER WEAPON'],
 [207.0, 'OTHER KNIFE'],
 [212.0, 'BOTTLE'],
 [511.0, 'VERBAL THREAT'],
 [213.0, 'CLEAVER'],
 [204.0, 'FOLDING KNIFE'],
 [301.0, 'BELT FLAILING INSTRUMENT/CHAIN'],
 [200.0, 'KNIFE WITH BLADE 6INCHES OR LESS'],
 [302.0, 'BLUNT INSTRUMENT'],
 [515.0, 'PHYSICAL PRESENCE'],
 [501.0, 'BOMB THREAT'],
 [219.0, 'SCREWDRIVER'],
 [512.0, 'MACE/PEPPER SPRAY'],
 [509.0, 'ROPE/LIGATURE'],
 [205.0, 'KITCHEN KNIFE'],
 [101.0, 'REVOLVER'],
 [201.0, 'KNIFE WITH BLADE OVER 6 INCHES IN LENGTH'],
 [306.0, 'ROCK/THROWN OBJECT'],
 [102.0, 'HAND GUN'],
 [210.0, 'RAZOR BLADE'],
 [312.0, 'PIPE/METAL PIPE'],
 [218.0, 'OTHER CUTTING INSTRUMENT'],
 [106.0, 'UNKNOWN FIREARM'],
 [308.0, 'STICK'],
 [304.0, 'CLUB/BAT'],
 [109.0, 'SEMI-AUTOMATIC PISTOL'],
 [223.0, 'UNKNOWN TYPE CUTTING INSTRUMENT'],
 [309.0, 'BOARD'],
 [310.0, 'CONCRETE BLOCK/BRICK'],
 [114.0, 'AIR PISTOL/REVOLVER/RIFLE/BB GUN'],
 [216.0, 'SCISSORS'],
 [514.0, 'TIRE IRON'],
 [510.0, 'SCALDING LIQUID'],
 [113.0, 'SIMULATED GUN'],
 [307.0, 'VEHICLE'],
 [206.0, 'SWITCH BLADE'],
 [215.0, 'MACHETE'],
 [107.0, 'OTHER FIREARM'],
 [103.0, 'RIFLE'],
 [202.0, 'BOWIE KNIFE'],
 [104.0, 'SHOTGUN'],
 [112.0, 'TOY GUN'],
 [220.0, 'SYRINGE'],
 [203.0, 'DIRK/DAGGER'],
 [503.0, 'CAUSTIC CHEMICAL/POISON'],
 [125.0, 'RELIC FIREARM'],
 [208.0, 'RAZOR'],
 [506.0, 'FIRE'],
 [122.0, 'HECKLER & KOCH 93 SEMIAUTOMATIC ASSAULT RIFLE'],
 [311.0, 'HAMMER'],
 [513.0, 'STUN GUN'],
 [305.0, 'FIXED OBJECT'],
 [214.0, 'ICE PICK'],
 [504.0, 'DEMAND NOTE'],
 [108.0, 'AUTOMATIC WEAPON/SUB-MACHINE GUN'],
 [303.0, 'BRASS KNUCKLES'],
 [217.0, 'SWORD'],
 [211.0, 'AXE'],
 [221.0, 'GLASS'],
 [118.0, 'UZI SEMIAUTOMATIC ASSAULT RIFLE'],
 [105.0, 'SAWED OFF RIFLE/SHOTGUN'],
 [121.0, 'HECKLER & KOCH 91 SEMIAUTOMATIC ASSAULT RIFLE'],
 [300.0, 'BLACKJACK'],
 [507.0, 'LIQUOR/DRUGS'],
 [124.0, 'M-14 SEMIAUTOMATIC ASSAULT RIFLE'],
 [111.0, 'STARTER PISTOL/REVOLVER'],
 [505.0, 'EXPLOXIVE DEVICE'],
 [508.0, 'MARTIAL ARTS WEAPONS'],
 [117.0, 'UNK TYPE SEMIAUTOMATIC ASSAULT RIFLE'],
 [115.0, 'ASSAULT WEAPON/UZI/AK47/ETC'],
 [209.0, 'STRAIGHT RAZOR'],
 [110.0, 'SEMI-AUTOMATIC RIFLE'],
 [502.0, 'BOW AND ARROW'],
 [119.0, 'MAC-10 SEMIAUTOMATIC ASSAULT WEAPON'],
 [222.0, nan],
 [116.0, 'ANTIQUE FIREARM'],
 [120.0, 'MAC-11 SEMIAUTOMATIC ASSAULT WEAPON'],
 [516.0, 'DOG/ANIMAL (SIC ANIMAL ON)'],
 [123.0, 'M1-1 SEMIAUTOMATIC ASSAULT RIFLE']]

### 1.1.8 Crime Code

In [89]:
crime_dict = make_dict(data, 'Crime Code', 'Crime Code Description')

In [90]:
crime_dict

{626: 'INTIMATE PARTNER - SIMPLE ASSAULT',
 510: 'VEHICLE - STOLEN',
 745: 'VANDALISM - MISDEAMEANOR ($399 OR UNDER)',
 110: 'CRIMINAL HOMICIDE',
 668: 'EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)',
 440: 'THEFT PLAIN - PETTY ($950 & UNDER)',
 763: 'STALKING',
 442: 'SHOPLIFTING - PETTY THEFT ($950 & UNDER)',
 624: 'BATTERY - SIMPLE ASSAULT',
 670: 'EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)',
 649: 'DOCUMENT FORGERY / STOLEN FELONY',
 480: 'BIKE - STOLEN',
 210: 'ROBBERY',
 821: 'SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH 0007=02',
 220: 'ATTEMPTED ROBBERY',
 437: 'RESISTING ARREST',
 888: 'TRESPASSING',
 341: 'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD0036',
 660: 'COUNTERFEIT',
 230: 'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT',
 647: 'THROWING OBJECT AT MOVING VEHICLE',
 951: 'DEFRAUDING INNKEEPER/THEFT OF SERVICES, $400 & UNDER',
 930: 'CRIMINAL THREATS - NO WEAPON DISPLAYED',
 740: 'VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS) 0114',
 330: 'BURGLARY FROM VEHICLE',
 860: 'BATTERY WITH SEXUAL CONTACT',
 946: 'OTHER MISCELLANEOUS CRIME',
 310: 'BURGLARY',
 343: 'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)',
 627: 'CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT',
 850: 'INDECENT EXPOSURE',
 237: 'CHILD NEGLECT (SEE 300 W.I.C.)',
 625: 'OTHER ASSAULT',
 350: 'THEFT, PERSON',
 755: 'BOMB SCARE',
 940: 'EXTORTION',
 121: 'RAPE, FORCIBLE',
 441: 'THEFT PLAIN - ATTEMPT',
 331: 'THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER)',
 236: 'INTIMATE PARTNER - AGGRAVATED ASSAULT',
 886: 'DISTURBING THE PEACE',
 813: 'CHILD ANNOYING (17YRS & UNDER)',
 251: 'SHOTS FIRED AT INHABITED DWELLING',
 623: 'BATTERY POLICE (SIMPLE)',
 761: 'BRANDISH WEAPON',
 943: 'CRUELTY TO ANIMALS',
 815: 'SEXUAL PENTRATION WITH A FOREIGN OBJECT',
 354: 'THEFT OF IDENTITY',
 648: 'ARSON',
 320: 'BURGLARY, ATTEMPTED',
 420: 'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)',
 900: 'VIOLATION OF COURT ORDER',
 956: 'LETTERS, LEWD',
 812: 'CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)0060',
 410: 'BURGLARY FROM VEHICLE, ATTEMPTED',
 434: 'FALSE IMPRISONMENT',
 662: 'BUNCO, GRAND THEFT',
 351: 'PURSE SNATCHING',
 901: 'VIOLATION OF RESTRAINING ORDER',
 122: 'RAPE, ATTEMPTED',
 664: 'BUNCO, PETTY THEFT',
 910: 'KIDNAPPING',
 762: 'LEWD CONDUCT',
 933: 'PROWLER',
 520: 'VEHICLE - ATTEMPT STOLEN',
 805: 'PIMPING',
 840: 'BEASTIALITY, CRIME AGAINST NATURE SEXUAL ASSLT WITH ANIM0065',
 932: 'PEEPING TOM',
 810: 'SEX, UNLAWFUL',
 485: 'BIKE - ATTEMPTED STOLEN',
 450: 'THEFT FROM PERSON - ATTEMPT',
 352: 'PICKPOCKET',
 438: 'RECKLESS DRIVING',
 820: 'ORAL COPULATION',
 928: 'THREATENING PHONE CALLS/LETTERS',
 444: 'DISHONEST EMPLOYEE - PETTY THEFT',
 661: 'UNAUTHORIZED COMPUTER ACCESS',
 753: 'DISCHARGE FIREARMS/SHOTS FIRED',
 922: 'CHILD STEALING',
 653: 'CREDIT CARDS, FRAUD USE ($950.01 & OVER)',
 433: 'DRIVING WITHOUT OWNER CONSENT (DWOC)',
 666: 'BUNCO, ATTEMPT',
 942: 'BRIBERY',
 654: 'CREDIT CARDS, FRAUD USE ($950 & UNDER',
 756: 'WEAPONS POSSESSION/BOMBING',
 235: 'CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT',
 231: 'ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER',
 443: 'SHOPLIFTING - ATTEMPT',
 949: 'ILLEGAL DUMPING',
 920: 'KIDNAPPING - GRAND ATTEMPT',
 452: 'PICKPOCKET, ATTEMPT',
 451: 'PURSE SNATCHING - ATTEMPT',
 421: 'THEFT FROM MOTOR VEHICLE - ATTEMPT',
 622: 'BATTERY ON A FIREFIGHTER',
 651: 'DOCUMENT WORTHLESS ($200.01 & OVER)',
 890: 'FAILURE TO YIELD',
 902: 'VIOLATION OF TEMPORARY RESTRAINING ORDER',
 439: 'FALSE POLICE REPORT',
 345: 'DISHONEST EMPLOYEE - GRAND THEFT',
 952: 'ABORTION/ILLEGAL',
 954: 'CONTRIBUTING',
 950: 'DEFRAUDING INNKEEPER/THEFT OF SERVICES, OVER $400',
 353: 'DRUNK ROLL',
 474: 'THEFT, COIN MACHINE - PETTY ($950 & UNDER)',
 487: 'BOAT - STOLEN',
 880: 'DISRUPT SCHOOL',
 882: 'INCITING A RIOT',
 884: 'FAILURE TO DISPERSE',
 806: 'PANDERING',
 471: 'TILL TAP - PETTY ($950 & UNDER)',
 436: 'LYNCHING - ATTEMPTED',
 944: 'CONSPIRACY',
 931: 'REPLICA FIREARMS(SALE,DISPLAY,MANUFACTURE OR DISTRIBUTE)0132',
 870: 'CHILD ABANDONMENT',
 924: 'TELEPHONE PROPERTY - DAMAGE',
 903: 'CONTEMPT OF COURT',
 865: 'DRUGS, TO A MINOR',
 250: 'SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT',
 347: 'GRAND THEFT / INSURANCE FRAUD',
 473: 'THEFT, COIN MACHINE - GRAND ($950.01 & OVER)',
 349: 'GRAND THEFT / AUTO REPAIR',
 446: 'PETTY THEFT - AUTO REPAIR',
 435: 'LYNCHING',
 113: 'MANSLAUGHTER, NEGLIGENT',
 948: 'BIGAMY',
 472: 'TILL TAP - ATTEMPT',
 470: 'TILL TAP - GRAND THEFT ($950.01 & OVER)',
 822: nan,
 453: 'DRUNK ROLL - ATTEMPT',
 475: 'THEFT, COIN MACHINE - ATTEMPT',
 652: 'DOCUMENT WORTHLESS ($200 & UNDER)',
 760: nan,
 921: nan,
 814: nan,
 445: 'DISHONEST EMPLOYEE ATTEMPTED THEFT',
 830: 'INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES)',
 432: 'BLOCKING DOOR INDUCTION CENTER',
 926: 'TRAIN WRECKING'}

In [72]:
len(crime_dict)

138

In [98]:
pd.DataFrame(list(crime_dict.items()), columns=['Crime Code', 'Crime Description']).to_csv('../data/crime_codes.csv')

In [112]:
crimesTime = data['Time Occurred']
crimesTimeName = []
mornCount = 0
afterCount = 0
evenCount = 0
nightCount = 0
#set each time to morning, afternoon, evening or night 

for i in crimesTime:
    if i in range(500, 1159):
        crimesTimeName.append("Morning")
        mornCount += 1
    elif i in range(1200,1659):
        crimesTimeName.append("Afternoon")
        afterCount += 1
    elif i in range(1700, 2059):
        crimesTimeName.append("Evening")
        evenCount += 1
    else:
        crimesTimeName.append("Night")
        nightCount += 1
    
data['Time of Day'] = crimesTimeName

print(len(data))
print(len(crimesTime))

print('Crimes committed in the morning:',mornCount)
print('Crimes committed in the afternoon:',afterCount)
print('Crimes committed in the evening:',evenCount)
print('Crimes committed in the night:',nightCount)

1584316
1584316
Crimes committed in the morning: 343447
Crimes committed in the afternoon: 436065
Crimes committed in the evening: 363830
Crimes committed in the night: 440974

In [109]:
len(data['Crime Code'])
len(data)

tempdf = data['Time Occurred']
templist = []

for i in tempdf:
    if 500 >= i >= 1159:
        templist.append(0)
    elif 1200 >= i >= 1659:
        templist.append(1)
    elif 1700 >= i >= 2059:
        templist.append(2)
    else:
        templist.append(3)

data['Time of Day'] = templist

print(len(templist))
print(len(data))
print(len(tempdf))

1584316
1584316
1584316

In [108]:
type(tempdf)

pandas.core.series.Series

### 1.1.9 Premise Code

In [51]:
premise_dict = make_dict(data, 'Premise Code', 'Premise Description')

In [52]:
premise_dict

[[],
 [502.0, 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'],
 [101.0, 'STREET'],
 [501.0, 'SINGLE FAMILY DWELLING'],
 [108.0, 'PARKING LOT'],
 [203.0, 'OTHER BUSINESS'],
 [404.0, 'DEPARTMENT STORE'],
 [102.0, 'SIDEWALK'],
 [406.0, 'OTHER STORE'],
 [735.0, 'NIGHT CLUB (OPEN EVENINGS ONLY)'],
 [701.0, 'HOSPITAL'],
 [732.0, 'POST OFFICE'],
 [122.0, 'VEHICLE, PASSENGER/TRUCK'],
 [402.0, 'MARKET'],
 [201.0, 'JEWELRY STORE'],
 [210.0, 'RESTAURANT/FAST FOOD'],
 [710.0, 'OTHER PREMISE'],
 [716.0, 'THEATRE/MOVIE'],
 [504.0, 'OTHER RESIDENCE'],
 [511.0, 'PROJECT/TENEMENT/PUBLIC HOUSING'],
 [207.0, 'BAR/COCKTAIL/NIGHTCLUB'],
 [719.0, 'MEDICAL/DENTAL OFFICES'],
 [107.0, 'VACANT LOT'],
 [104.0, 'DRIVEWAY'],
 [726.0, 'POLICE FACILITY'],
 [110.0, 'FREEWAY'],
 [503.0, 'HOTEL'],
 [405.0, 'CLOTHING STORE'],
 [403.0, 'DRUG STORE'],
 [109.0, 'PARK/PLAYGROUND'],
 [248.0, 'CELL PHONE STORE'],
 [717.0, 'HEALTH SPA/GYM'],
 [116.0, 'OTHER/OUTSIDE'],
 [407.0, 'HARDWARE/BUILDING SUPPLY'],
 [103.0, 'ALLEY'],
 [244.0, 'TOBACCO SHOP'],
 [124.0, 'BUS STOP'],
 [216.0, 'SWAP MEET'],
 [401.0, 'MINI-MART'],
 [120.0, 'STORAGE SHED'],
 [707.0, 'GARAGE/CARPORT'],
 [721.0, 'HIGH SCHOOL'],
 [221.0, 'PUBLIC STORAGE'],
 [123.0, 'PARKING UNDERGROUND/BUILDING'],
 [702.0, 'OFFICE BUILDING/OFFICE'],
 [213.0, 'WAREHOUSE'],
 [737.0, 'SKATING RINK*'],
 [713.0, 'CONVENTION CENTER'],
 [602.0, 'BANK'],
 [709.0, 'PUBLIC RESTROOM(INDOORS-INSIDE)'],
 [148.0, 'PUBLIC RESTROOM/OUTSIDE*'],
 [106.0, 'TUNNEL'],
 [725.0, 'GOVERNMENT FACILITY (FEDERAL,STATE, COUNTY & CITY)'],
 [217.0, 'AUTO REPAIR SHOP'],
 [738.0, 'LIBRARY'],
 [753.0, 'DETENTION/JAIL FACILITY'],
 [118.0, 'CONSTRUCTION SITE'],
 [724.0, 'TRADE SCHOOL (MEDICAL-TECHNICAL-BUSINESS)*'],
 [121.0, 'YARD (RESIDENTIAL/BUSINESS)'],
 [301.0, 'GAS STATION'],
 [741.0, 'STAPLES CENTER *'],
 [708.0, 'CHURCH/CHAPEL (CHANGED 03-03 FROM CHURCH/TEMPLE)'],
 [507.0, 'CONDOMINIUM/TOWNHOUSE'],
 [220.0, 'NAIL SALON'],
 [811.0, 'OTHER RR TRAIN (UNION PAC, SANTE FE ETC'],
 [202.0, 'LIQUOR STORE'],
 [802.0, 'MUNICIPAL BUS LINE INCLUDES LADOT/DASH'],
 [514.0, 'GROUP HOME'],
 [235.0, 'PHARMACY INSIDE STORE OR SUPERMARKET*'],
 [733.0, 'BAR/SPORTS BAR (OPEN DAY & NIGHT)'],
 [252.0, "COFFEE SHOP (STARBUCKS, COFFEE BEAN, PEET'S, ETC.)"],
 [304.0, 'GARMENT MANUFACTURER'],
 [146.0, 'PATIO*'],
 [729.0, 'SPECIALTY SCHOOL/OTHER'],
 [215.0, 'TRAIN DEPOT'],
 [114.0, 'TAXI'],
 [801.0, 'MTA BUS'],
 [720.0, 'JUNIOR HIGH SCHOOL'],
 [727.0, 'SHOPPING MALL (COMMON AREA)'],
 [704.0, 'ELEMENTARY SCHOOL'],
 [409.0, 'BEAUTY SUPPLY STORE'],
 [208.0, 'AUTO SALES LOT'],
 [739.0, 'SPORTS ARENA'],
 [222.0, 'LAUNDROMAT'],
 [302.0, 'FACTORY'],
 [249.0, 'NURSERY/FLOWER SHOP'],
 [714.0, 'DODGER STADIUM'],
 [752.0, 'FIRE STATION'],
 [129.0, 'TERMINAL'],
 [229.0, 'CHECK CASHING*'],
 [105.0, 'PEDESTRIAN OVERCROSSING'],
 [239.0, 'MEDICAL MARIJUANA FACILITIES/BUSINESSES'],
 [730.0, 'SYNAGOGUE/TEMPLE'],
 [605.0, 'AUTOMATED TELLER MACHINE (ATM)'],
 [112.0, 'BUS, SCHOOL, CHURCH'],
 [230.0, 'DAY CARE/ADULTS*'],
 [711.0, 'ARCADE,GAME ROOM/VIDEO GAMES (EXAMPLE CHUCKIE CHEESE)*'],
 [212.0, 'TRANSPORTATION FACILITY (AIRPORT)'],
 [214.0, 'BUS DEPOT'],
 [510.0, 'NURSING/CONVALESCENT/RETIREMENT HOME'],
 [509.0, "MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV'S/MOTORHOME"],
 [703.0, 'ENTERTAINMENT/COMEDY CLUB (OTHER)'],
 [242.0, 'DISCOUNT STORE (99 CENT,DOLLAR,ETC.'],
 [218.0, 'BEAUTY/BARBER SHOP'],
 [111.0, 'CHARTER BUS AND PRIVATELY OWNED BUS'],
 [128.0, 'BUS STOP OR LAYOVER'],
 [151.0, 'TOW YARD*'],
 [740.0, 'OTHER PLACE OF WORSHIP'],
 [723.0, 'PRIVATE SCHOOL/PRESCHOOL'],
 [411.0, 'PET STORE'],
 [204.0, 'MANUFACTURING COMPANY'],
 [233.0, 'TATTOO PARLOR*'],
 [728.0, 'ELEVATOR'],
 [508.0, 'FRAT HOUSE/SORORITY/DORMITORY'],
 [603.0, 'CREDIT UNION'],
 [751.0, 'WEBSITE'],
 [205.0, 'GUN/SPORTING GOODS'],
 [126.0, 'TRAIN'],
 [135.0, 'MTA PROPERTY OR PARKING LOT'],
 [147.0, 'POOL-PUBLIC/OUTDOOR OR INDOOR*'],
 [228.0, 'BOWLING ALLEY*'],
 [232.0, 'DELIVERY SERVICE (FED EX, UPS, COURIERS,COURIER SERVICE)*'],
 [506.0, 'ABANDONED BUILDING ABANDONED HOUSE'],
 [743.0, 'MASS GATHERING LOCATION'],
 [156.0, 'VALET'],
 [150.0, 'TOOL SHED*'],
 [505.0, 'MOTEL'],
 [243.0, "DIY CENTER (LOWE'S,HOME DEPOT,OSH,CONTRACTORS WAREHOUSE)"],
 [231.0, 'DAY CARE/CHILDREN*'],
 [806.0, 'REDLINE (SUBWAY TRAIN)'],
 [138.0, 'STAIRWELL*'],
 [145.0, 'MAIL BOX'],
 [722.0, 'COLLEGE/JUNIOR COLLEGE/UNIVERSITY'],
 [119.0, 'PORCH, RESIDENTIAL'],
 [125.0, 'PAY PHONE'],
 [211.0, 'PAWN SHOP'],
 [206.0, 'TV/RADIO/APPLIANCE'],
 [245.0, 'CATERING/ICE CREAM TRUCK'],
 [236.0, 'VISION CARE FACILITY*'],
 [223.0, 'VIDEO RENTAL STORE'],
 [742.0, 'SPORTS VENUE, OTHER'],
 [247.0, 'CAR WASH'],
 [140.0, 'BALCONY*'],
 [706.0, 'SEX ORIENTED/BOOK STORE'],
 [250.0, 'COMPUTER SERVICES/REPAIRS/SALES'],
 [718.0, 'MASSAGE PARLOR'],
 [131.0, 'REDLINE SUBWAY PLATFORM'],
 [251.0, 'RECYCLING CENTER'],
 [225.0, 'RECORD-CD MUSIC/COMPUTER GAME STORE'],
 [246.0, 'METHADONE CLINIC'],
 [604.0, 'FINANCE COMPANY'],
 [408.0, 'AUTO SUPPLY STORE*'],
 [237.0, 'HOSPICE'],
 [209.0, 'EQUIPMENT RENTAL'],
 [809.0, 'METROLINK TRAIN'],
 [712.0, 'COLISEUM'],
 [607.0, 'BANKING INSIDE MARKET-STORE *'],
 [115.0, 'AIRCRAFT'],
 [219.0, 'CLEANER/LAUNDROMAT'],
 [142.0, 'DRIVE THRU*'],
 [149.0, 'RIVER BED*'],
 [152.0, 'UNDERPASS/BRIDGE*'],
 [253.0, 'MORTUARY'],
 [705.0, 'SLIPS/DOCK/MARINA/BOAT'],
 [117.0, 'BEACH'],
 [303.0, 'OIL REFINERY'],
 [748.0, 'CULTURAL SIGNIFICANCE/MONUMENT'],
 [141.0, 'CEMETARY*'],
 [410.0, 'MEMBERSHIP STORE (COSTCO,SAMS CLUB)*'],
 [130.0, 'REDLINE ENTRANCE/EXIT'],
 [745.0, 'WATER FACILITY'],
 [736.0, 'SKATEBOARD FACILITY/SKATEBOARD PARK*'],
 [238.0, 'TELECOMMUNICATION FACILITY/LOCATION'],
 [144.0, 'GOLF COURSE*'],
 [234.0, 'OPTICAL OFFICE INSIDE STORE OR SUPERMARKET*'],
 [512.0, 'FOSTER HOME BOYS OR GIRLS*'],
 [750.0, 'CYBERSPACE'],
 [139.0, 'AMUSEMENT PARK*'],
 [746.0, 'SEWAGE FACILITY/PIPE'],
 [734.0, 'HOCKEY RINK/ICE HOCKEY'],
 [133.0, 'REDLINE SUBWAY RAIL CAR (INSIDE TRAIN)'],
 [132.0, 'REDLINE SUBWAY MEZZANINE'],
 [804.0, 'GREYHOUND OR INTERSTATE BUS'],
 [113.0, 'TRUCK, COMMERICAL'],
 [754.0, 'MUSEUM'],
 [731.0, 'MOSQUE*'],
 [601.0, 'SAVINGS & LOAN'],
 [305.0, 'CHEMICAL STORAGE/MANUFACTURING PLANT'],
 [606.0, 'DRIVE THRU BANKING (WINDOW)*'],
 [134.0, 'REDLINE SUBWAY TUNNEL'],
 [715.0, 'HORSE RACING/SANTA ANITA PARK*'],
 [513.0, 'ABATEMENT LOCATION'],
 [810.0, 'AMTRAK TRAIN'],
 [744.0, 'HIGH-RISE BUILDING'],
 [127.0, 'TRASH CAN/TRASH DUMPSTER'],
 [227.0, 'ABORTION CLINIC/ABORTION FACILITY*'],
 [803.0, 'RETIRED (DUPLICATE) DO NOT USE THIS CODE'],
 [807.0, 'BLUE LINE (ABOVE GROUND SURFACE TRAIN)'],
 [154.0, 'TRAIN TRACKS'],
 [143.0, 'ESCALATOR*'],
 [136.0, 'OTHER INTERSTATE, CHARTER BUS'],
 [137.0, 'TRAM/STREETCAR(BOXLIKE WAG ON RAILS)*'],
 [153.0, 'ORANGE LINE PARKING LOT'],
 [155.0, 'DAM/RESERVOIR'],
 [241.0, 'ENERGY PLANT/FACILITY'],
 [808.0, 'GREEN LINE (I-105 FWY LEVEL TRAIN)'],
 [517.0, nan],
 [255.0, nan],
 [608.0, 'BANK DROP BOX/MONEY DROP-OUTSIDE OF BANK*'],
 [516.0, nan],
 [515.0, nan],
 [412.0, nan],
 [413.0, nan],
 [755.0, nan],
 [749.0, 'TACTICAL SIGNIFICANCE'],
 [414.0, nan],
 [805.0, 'RETIRED (DUPLICATE) DO NOT USE THIS CODE'],
 [518.0, nan],
 [254.0, nan],
 [158.0, nan],
 [157.0, nan],
 [747.0, 'NUCLEAR FACILITY'],
 [240.0, 'DEPT OF DEFENSE FACILITY'],
 [226.0, 'RETIRED (DUPLICATE) DO NOT USE THIS CODE'],
 [918.0, nan],
 [903.0, nan],
 [835.0, nan],
 [834.0, nan],
 [907.0, nan],
 [906.0, nan],
 [946.0, nan],
 [949.0, nan],
 [964.0, nan],
 [968.0, nan],
 [224.0, 'SURPLUS SURVIVAL STORE'],
 [910.0, nan],
 [953.0, nan],
 [908.0, nan],
 [893.0, nan],
 [838.0, nan],
 [913.0, nan],
 [869.0, nan],
 [912.0, nan],
 [885.0, nan],
 [957.0, nan],
 [940.0, nan],
 [900.0, nan],
 [757.0, nan],
 [945.0, nan],
 [943.0, nan],
 [935.0, nan],
 [904.0, nan],
 [952.0, nan],
 [876.0, nan],
 [875.0, nan],
 [956.0, nan],
 [416.0, nan],
 [936.0, nan],
 [942.0, nan],
 [922.0, nan],
 [880.0, nan],
 [947.0, nan],
 [911.0, nan],
 [971.0, nan],
 [937.0, nan],
 [921.0, nan],
 [941.0, nan],
 [897.0, nan],
 [966.0, nan],
 [932.0, nan],
 [917.0, nan],
 [931.0, nan],
 [967.0, nan],
 [902.0, nan],
 [901.0, nan],
 [915.0, nan],
 [916.0, nan],
 [919.0, nan],
 [950.0, nan],
 [944.0, nan],
 [963.0, nan],
 [909.0, nan],
 [519.0, nan],
 [871.0, nan],
 [934.0, nan],
 [951.0, nan],
 [868.0, nan],
 [894.0, nan],
 [836.0, nan],
 [905.0, nan],
 [874.0, nan],
 [958.0, nan],
 [961.0, nan],
 [969.0, nan],
 [920.0, nan],
 [872.0, nan]]

### 1.1.10 Area ID

In [61]:
area_dict = make_dict(data, 'Area ID', 'Area Name')

In [62]:
area_dict

[[],
 [12, '77th Street'],
 [20, 'Olympic'],
 [18, 'Southeast'],
 [21, 'Topanga'],
 [1, 'Central'],
 [11, 'Northeast'],
 [16, 'Foothill'],
 [19, 'Mission'],
 [9, 'Van Nuys'],
 [13, 'Newton'],
 [15, 'N Hollywood'],
 [10, 'West Valley'],
 [14, 'Pacific'],
 [17, 'Devonshire'],
 [2, 'Rampart'],
 [3, 'Southwest'],
 [4, 'Hollenbeck'],
 [5, 'Harbor'],
 [6, 'Hollywood'],
 [8, 'West LA'],
 [7, 'Wilshire']]

# Make Dict Function

In [80]:
def make_dict(data, code, desc):    
    codes = data[code].unique()
    d = {}
    for i in codes:
        temp = data[data[code] == i]
        if not temp.empty:
            d.update({i : temp[desc].iloc[0]})
    return d

## 1.3 Compute Correlation Matrix

In [84]:
'''
Compute Correlation Matrix

Columns with High Correlation:
* Note: ignore crime codes 1 - 4
    99% : DR Number and Year
    99% : Area ID and Reporting District
    43% : Crime Code and Weapon Used Code
    99% : Crime Code and Crime Code 1
    17% : Victim Age and Premise Code
    -11% : Victim Age and Crime Code 4
    31% : Victim Age and Victim Sex
    17% : Victim Age and Victim Descent
    32% : Victim Sex and Victim Descent
    12% : Victim Sex and Premise Code
    19% : Victim Sex and Weapon Used Code
    15% : Victim Descent and Premise Code
    22% : Premise Code and Weapon Used Code
    17% : Premise Code and Crime Code 4
    43% : Weapon Used Code and Crime Code 1
    12% : Crime Code 1 and Crime Code 3
    26% : Crime Code 2 and Crime Code 3
    27% : Crime Code 2 and Crime Code 4
    51% : Crime Code 3 and Crime Code 4
'''
print(data2.columns)
data2.corr()

Index(['DR Number', 'Date Reported', 'Date Occurred', 'Time Occurred',
       'Area ID', 'Reporting District', 'Crime Code', 'Victim Age',
       'Victim Sex', 'Victim Descent', 'Premise Code', 'Weapon Used Code',
       'Status Code', 'Location ', 'Longitude', 'Latitude', 'Month', 'Day',
       'Year'],
      dtype='object')

,DR Number,Time Occurred,Area ID,Reporting District,Crime Code,Victim Age,Victim Sex,Victim Descent,Premise Code,Weapon Used Code,Longitude,Latitude,Month,Day,Year
DR Number,1.000000,-0.007390,0.016191,0.016248,-0.009166,0.007397,0.029931,0.009186,-0.015414,0.000441,-0.073152,0.073512,-0.066488,-0.003282,0.990360
Time Occurred,-0.007390,1.000000,0.011809,0.012023,0.017712,-0.049945,0.035793,-0.026228,-0.095394,-0.002821,-0.001711,0.002018,0.004076,0.023921,0.001187
Area ID,0.016191,0.011809,1.000000,0.998998,-0.004587,0.009835,0.010270,0.026257,0.014475,-0.000490,0.019657,-0.004529,-0.002669,-0.004693,-0.011645
Reporting District,0.016248,0.012023,0.998998,1.000000,-0.004624,0.010262,0.010168,0.025982,0.014411,-0.000368,0.019397,-0.004453,-0.002571,-0.004631,-0.011553
Crime Code,-0.009166,0.017712,-0.004587,-0.004624,1.000000,-0.034478,0.076948,-0.024452,0.098754,0.432260,0.000083,0.000468,-0.003484,-0.006296,-0.008273
Victim Age,0.007397,-0.049945,0.009835,0.010262,-0.034478,1.000000,-0.311614,0.270187,0.167376,0.074359,-0.000926,0.001905,0.000373,-0.012514,0.003336
Victim Sex,0.029931,0.035793,0.010270,0.010168,0.076948,-0.311614,1.000000,-0.322066,-0.118282,0.185867,-0.003341,0.001501,0.002633,0.000329,0.030298
Victim Descent,0.009186,-0.026228,0.026257,0.025982,-0.024452,0.270187,-0.322066,1.000000,0.151079,0.064199,0.001616,0.004579,-0.002049,-0.001794,0.006586
Premise Code,-0.015414,-0.095394,0.014475,0.014411,0.098754,0.167376,-0.118282,0.151079,1.000000,0.216194,0.001442,-0.000655,-0.007148,-0.026643,-0.027087
Weapon Used Code,0.000441,-0.002821,-0.000490,-0.000368,0.432260,0.074359,0.185867,0.064199,0.216194,1.000000,0.000776,0.000791,-0.004215,-0.011911,-0.002589
Longitude,-0.073152,-0.001711,0.019657,0.019397,0.000083,-0.000926,-0.003341,0.001616,0.001442,0.000776,1.000000,-0.998703,0.011146,-0.005992,-0.073257
Latitude,0.073512,0.002018,-0.004529,-0.004453,0.000468,0.001905,0.001501,0.004579,-0.000655,0.000791,-0.998703,1.000000,-0.011502,0.005717,0.073105
Month,-0.066488,0.004076,-0.002669,-0.002571,-0.003484,0.000373,0.002633,-0.002049,-0.007148,-0.004215,0.011146,-0.011502,1.000000,0.012178,-0.073225
Day,-0.003282,0.023921,-0.004693,-0.004631,-0.006296,-0.012514,0.000329,-0.001794,-0.026643,-0.011911,-0.005992,0.005717,0.012178,1.000000,0.004918
Year,0.990360,0.001187,-0.011645,-0.011553,-0.008273,0.003336,0.030298,0.006586,-0.027087,-0.002589,-0.073257,0.073105,-0.073225,0.004918,1.000000

In [85]:
# remove status code, seems useless
# remove location and Date Occurred
data3 = data2[['DR Number', 'Month', 'Day', 'Year', 'Time Occurred',
       'Area ID', 'Reporting District', 'Crime Code', 'Victim Age', 'Victim Sex',
       'Victim Descent', 'Premise Code',
       'Weapon Used Code', 'Longitude', 'Latitude']]

In [86]:
data3.to_csv('../data/Crime_Data_2010_2017_clean.csv')

In [ ]:
# Remove Nulls
#data2 = data2.loc[data2['Location '].notnull()]